package com.wzu.appmanager.dao;

import com.wzu.appmanager.pojo.AdPromotion;
import java.util.List;

public interface AdPromotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_promotion
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_promotion
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int insert(AdPromotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_promotion
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    AdPromotion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_promotion
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    List<AdPromotion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_promotion
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int updateByPrimaryKey(AdPromotion record);
}