package com.wzu.appmanager.dao;

import com.wzu.appmanager.pojo.AppCategory;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int insert(AppCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    AppCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    List<AppCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int updateByPrimaryKey(AppCategory record);

    List<AppCategory> getAppCategoryListByParentId(@Param("parentId")Integer parentId);
}