package com.wzu.appmanager.dao;

import com.wzu.appmanager.pojo.AppVersion;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public interface AppVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int insert(AppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    AppVersion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    List<AppVersion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int updateByPrimaryKey(AppVersion record);

    public List<AppVersion> getAppVersionList(@Param("appId")Integer appId) throws Exception;
//    appId,versionNo,versionInfo,publishStatus,
//    downloadLink,versionSize,apkLocPath,apkFileName,createdBy,creationDate
    public int add(AppVersion appVersion)throws Exception;

    public int getVersionCountByAppId(@Param("appId")Integer appId)throws Exception;

    public int deleteVersionByAppId(@Param("appId")Integer appId)throws Exception;

    public AppVersion getAppVersionById(@Param("id")Integer id)throws Exception;

    public int modify(AppVersion appVersion)throws Exception;

    public int deleteApkFile(@Param("id")Integer id)throws Exception;


}