package com.wzu.appmanager.dao;

import com.wzu.appmanager.pojo.BackendUser;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface BackendUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 通过userCode获取User
     * @param userCode
     * @return
     * @throws Exception
     */
    public BackendUser getLoginUser(@Param("userCode")String userCode)throws Exception;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int insert(BackendUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    BackendUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    List<BackendUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    int updateByPrimaryKey(BackendUser record);
}