package com.wzu.appmanager.pojo;

import org.omg.PortableInterceptor.INACTIVE;

import java.util.Date;

public class DevUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.id
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.devCode
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    private String devcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.devName
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    private String devname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.devPassword
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    private String devpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.devEmail
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    private String devemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.devInfo
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    private String devinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.createdBy
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    private Long createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.creationDate
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.modifyBy
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    private Long modifyby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dev_user.modifyDate
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    private Date modifydate;

    private Integer state;
    private String code;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Integer getState() {
        return state;
    }

    public DevUser(String devcode, String devpassword, String devemail, Integer state, String code ,String devname,String devinfo) {
        this.devcode = devcode;
        this.devpassword = devpassword;
        this.devemail = devemail;
        this.state = state;
        this.code =code;
        this.devname =devname;
        this.devinfo =devinfo;
    }
    public DevUser(){

    }
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.id
     *
     * @return the value of dev_user.id
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.id
     *
     * @param id the value for dev_user.id
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.devCode
     *
     * @return the value of dev_user.devCode
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public String getDevcode() {
        return devcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.devCode
     *
     * @param devcode the value for dev_user.devCode
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public void setDevcode(String devcode) {
        this.devcode = devcode == null ? null : devcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.devName
     *
     * @return the value of dev_user.devName
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public String getDevname() {
        return devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.devName
     *
     * @param devname the value for dev_user.devName
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public void setDevname(String devname) {
        this.devname = devname == null ? null : devname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.devPassword
     *
     * @return the value of dev_user.devPassword
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public String getDevpassword() {
        return devpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.devPassword
     *
     * @param devpassword the value for dev_user.devPassword
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public void setDevpassword(String devpassword) {
        this.devpassword = devpassword == null ? null : devpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.devEmail
     *
     * @return the value of dev_user.devEmail
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public String getDevemail() {
        return devemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.devEmail
     *
     * @param devemail the value for dev_user.devEmail
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public void setDevemail(String devemail) {
        this.devemail = devemail == null ? null : devemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.devInfo
     *
     * @return the value of dev_user.devInfo
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public String getDevinfo() {
        return devinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.devInfo
     *
     * @param devinfo the value for dev_user.devInfo
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public void setDevinfo(String devinfo) {
        this.devinfo = devinfo == null ? null : devinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.createdBy
     *
     * @return the value of dev_user.createdBy
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.createdBy
     *
     * @param createdby the value for dev_user.createdBy
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.creationDate
     *
     * @return the value of dev_user.creationDate
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.creationDate
     *
     * @param creationdate the value for dev_user.creationDate
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.modifyBy
     *
     * @return the value of dev_user.modifyBy
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public Long getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.modifyBy
     *
     * @param modifyby the value for dev_user.modifyBy
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public void setModifyby(Long modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dev_user.modifyDate
     *
     * @return the value of dev_user.modifyDate
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dev_user.modifyDate
     *
     * @param modifydate the value for dev_user.modifyDate
     *
     * @mbggenerated Sat Jun 06 17:59:00 CST 2020
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
}